In [1]:
import cv2
import numpy as np
import pandas as pd
import itertools

In [2]:
##### tarefas para fazer
## Algoritmos de detecção
# -- harris - OK
# -- sift - OK
# -- star/brisk OK
# -- entender parâmetros harris, sift, star e brisk (pendente)
# -- criar experimento para 25, 50, 100, 500, 1000 features
########################
## Algoritmos de descrição
# -- restringir área de checagem de pontos
# -- criar algoritmo para contar falsos positivos
## Imagem de teste
# -- preciso escolher qual o terceiro par de imagens para testar

# Experimento com detectores

# Códigos detectores

In [3]:
def detectHarrisKeypoints(image, threshold=0.01, blockSize=2, ksize=3, k=0.04):
    # Reading the image and converting the image to B/W 
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) 
    gray_image_f32 = np.float32(gray_image)

    # Applying the function 
    dst = cv2.cornerHarris(gray_image_f32, blockSize, ksize, k) 
  
    # dilate to mark the corners 
    dst = cv2.dilate(dst, None)
    
    ret, dst = cv2.threshold(dst,threshold*dst.max(),255,0)
    dst = np.uint8(dst)

    # find centroids
    ret, labels, stats, centroids = cv2.connectedComponentsWithStats(dst)

    # define the criteria to stop and refine the corners
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 0.001)
    corners = cv2.cornerSubPix(gray_image_f32,np.float32(centroids),(5,5),(-1,-1),criteria)

    # # extract keypoints
    # points = np.argwhere(dst > threshold * dst.max())
    
    keypoints = [cv2.KeyPoint(float(x[0]), float(x[1]), 13) for x in corners]

    # draw keypoints
    # image[dst > threshold * dst.max()] = [0, 255, 0]
    kp_image = cv2.drawKeypoints(image, keypoints, None, color=(255, 0, 0), flags=0)

    return keypoints, kp_image


In [4]:
def detectSIFTKeypoints(image, nfeatures=0, nOctaveLayers=3, contrastThreshold=0.04, edgeThreshold=10, sigma=1.6, enable_precise_upscale=False):
    # Reading the image and converting the image to B/W 
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) 
  
    # Applying the function 
    sift = cv2.SIFT_create(nfeatures, nOctaveLayers, contrastThreshold, edgeThreshold, sigma, enable_precise_upscale) 
    kp, des = sift.detectAndCompute(gray_image, None) 
    
    # Applying the function 
    kp_image = cv2.drawKeypoints(image, kp, None, color=(0, 255, 0), flags=0) 

    return kp, kp_image 

In [5]:
def detectStarKeypoints(image, max_size = 41, response_threshold = 30, line_threshold_projected = 10,
                        line_threshold_binarized = 8, suppress_nonmax_size = 5):
    # Reading the image and converting the image to B/W 
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) 
  
    # Applying the function 
    star = cv2.xfeatures2d.StarDetector_create(maxSize= max_size, 
                                        responseThreshold = response_threshold,
                                        lineThresholdProjected = line_threshold_projected,
                                        lineThresholdBinarized = line_threshold_binarized,
                                        suppressNonmaxSize = suppress_nonmax_size)
    kp = star.detect(gray_image, None)    

    # Applying the function 
    kp_image = cv2.drawKeypoints(image, kp, None, color=(0, 0, 255), flags=0) 

    return kp, kp_image 

In [6]:
# image = cv2.imread('../data/imgs/dsc07631.jpg')
# kp, kp_image = detectHarrisKeypoints(image, threshold=0.01, blockSize=2, ksize=3, k=0.02)
# print(len(kp))
# cv2.imshow('Star', kp_image) 
# cv2.waitKey() 

In [7]:
# def detectORBKeypoints(image, nfeatures=500, scaleFactor = 1.2, nlevels=8, edgeThreshold=31, WTA_K=2, patchSize=31):
#     # Reading the image and converting the image to B/W 
#     gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) 
  
#     # Applying the function 
#     orb = cv2.ORB_create(
#         nfeatures=nfeatures,
#         scaleFactor=scaleFactor,
#         nlevels=nlevels, 
#         edgeThreshold=edgeThreshold, 
#         WTA_K=WTA_K, 
#         patchSize=patchSize, 
#     ) 
#     kp, des = orb.detectAndCompute(gray_image, None)    

#     # Applying the function 
#     kp_image = cv2.drawKeypoints(image, kp, None, color=(0, 0, 255), flags=0) 

#     return kp, kp_image 

## Código comparando pontos

In [8]:
import numpy as np
from sklearn.metrics import pairwise_distances_argmin_min
from joblib import Parallel, delayed

def computeDistacesKeypoints(pts1, pts2, threshold=1):
    array_pts1 = np.asarray(pts1)
    array_pts2 = np.asarray(pts2)

    if array_pts1.shape[0] > 0 and array_pts2.shape[0] > 0:
        dists = pairwise_distances_argmin_min(array_pts1, array_pts2)  
        matches = [pts2[pt] for pt, dist in zip(dists[0], dists[1]) if dist <= threshold]
    else:
        matches = []
        
    return matches

In [9]:
def extract_and_save_features_csv(params, algol, path):
    if algol == 'star':
        func_var = detectStarKeypoints
    elif algol == 'harris':
        func_var = detectHarrisKeypoints
    else:
        func_var = detectSIFTKeypoints
    
    cols_name = [algol + '_' + param for param in list(params.keys())[1:]]
    cols_result = [algol + '_' + 'qtd_keypoints', algol + '_' + 'keypoints']
    df = pd.DataFrame(columns=cols_name+cols_result)
    
    keys = list(params)
    for values in itertools.product(*map(params.get, keys)):
        kps, kp_image = func_var(**dict(zip(keys, values)))
        kps_ = [(kp.pt[0], kp.pt[1]) for kp in kps] #kp.angle, kp.response, kp.octave, kp.class_id) for kp in kps]

        df.loc[len(df)] = list(values[1:]) + [len(kps_), kps_]

    df.to_csv(path, index=False)
    return df


def convert_to_kp(string_points):
    string_converted = list(eval(string_points))
    # kps = [cv2.KeyPoint(x[0], x[1], 13) for x in string_converted]
    # for p in string_converted:
    #     kp = cv2.KeyPoint(x=float(p[0]), y=float(p[1]), size=float(p[2]), angle=float(p[3]),
    #                 response=float(p[4]), octave=int(p[5]), class_id=int(p[6]))
    #     kps.append(kp)
    
    return string_converted

def comparing_keypoints_parallel(df, df1, df2, idx1, kp1_col, kp2_col, cols1, cols2, extra_cols):
    kp1 = df1.loc[idx1][kp1_col]
    df = pd.DataFrame(columns=cols1+cols2+extra_cols)
    for idx2 in df2.index:
        kp2 = df2.loc[idx2][kp2_col]
        matches = computeDistacesKeypoints(kp1, kp2, threshold=2)

        df.loc[len(df)] = df1.loc[idx1][cols1].tolist() + df2.loc[idx2][cols2].tolist() + [len(matches), matches]
    return df

def compare_and_save_match_points(df1, df2, kp1_col, kp2_col, path):
    cols1 = list(df1.columns[:-1])
    cols2 = list(df2.columns[:-1])
    extra_cols = ['qtd_matches', 'match_keypoints']

    df1_ = df1.copy()
    df2_ = df2.copy()

    df = pd.DataFrame(columns=cols1+cols2+extra_cols)
    dfs = []
    dfs = Parallel(n_jobs=-1)(delayed(comparing_keypoints_parallel)(df, df1_, df2_, idx1, kp1_col, kp2_col, cols1, cols2, extra_cols) for idx1 in df1_.index)
    df = pd.concat(dfs, ignore_index=True)
    # for idx1 in df1_.index:
    #     kp1 = df1_.loc[idx1][kp1_col]
    #     print(f'passou {idx1}')
    #     for idx2 in df2_.index:
    #         kp2 = df2_.loc[idx2][kp2_col]
    #         matches = computeDistacesKeypoints(kp1, kp2, threshold=2)

    #         df.loc[len(df)] = df1_.loc[idx1][cols1].tolist() + df2_.loc[idx2][cols2].tolist() + [len(matches), matches]
    df.to_csv(path, index=False)

    return df

## Salvando combinações de parâmetros dos algoritmos

In [27]:
image = cv2.imread('../data/imgs/dsc07631.jpg')

params_harris = {
    'image': [image],
    'threshold' : [0.005, 0.05, 0.1, 0.2],
    'blockSize' : [2, 4, 6, 8],
    'ksize' : [3, 5, 7, 9],
    'k' : [0.02, 0.04, 0.08, 0.16]
}

params_sift = {
    'image': [image],
    # 'nfeatures': [50, 100, 500, 1000],
    'nOctaveLayers' : [3, 5, 7, 9],
    'contrastThreshold' : [0.02, 0.04, 0.08, 0.1],
    'edgeThreshold' : [5, 10, 20, 40],
    'sigma' : [0.8, 1.6, 3.2, 6.4]
}

params_star = {
    'image': [image],
    'max_size': [11, 21, 41, 81],
    'response_threshold': [5, 10, 20, 30],
    'line_threshold_projected': [5, 10, 20, 30],
    'line_threshold_binarized': [4, 8, 16, 32],
    'suppress_nonmax_size': [2, 3, 5, 7]
}

# df_harris = extract_and_save_features_csv(params_harris, 'harris', '../data/results/dsc07631/harris_keypoints_1.csv')
# df_sift = extract_and_save_features_csv(params_sift, 'sift', '../data/results/dsc07631/sift_keypoints_1.csv')
# df_orb = extract_and_save_features_csv(params_star, 'star', '../data/results/dsc07631/star_keypoints_1.csv')


In [ ]:
df_harris = pd.read_csv('../data/results/dsc07631/harris_keypoints_1.csv')
df_sift = pd.read_csv('../data/results/dsc07631/sift_keypoints_1.csv')
df_star = pd.read_csv('../data/results/dsc07631/star_keypoints_1.csv')

In [15]:
kps1 = []
for idx in df_harris.index.tolist():
    kps1.append(convert_to_kp(df_harris['harris_keypoints'].loc[idx]))


In [12]:
kps2 = []
for idx in df_sift.index.tolist():
    kps2.append(convert_to_kp(df_sift['sift_keypoints'].loc[idx]))

In [13]:
kps3 = []
for idx in df_star.index.tolist():
    kps3.append(convert_to_kp(df_star['star_keypoints'].loc[idx]))

In [16]:
df_harris['harris_keypoints'] = kps1
df_sift['sift_keypoints'] = kps2
df_star['star_keypoints'] = kps3

In [58]:
df_hs = compare_and_save_match_points(df_harris, df_sift, 'harris_keypoints', 'sift_keypoints', '../data/results/dsc07631/harris_sift_matches.csv')

In [59]:
df_hst = compare_and_save_match_points(df_harris, df_star, 'harris_keypoints', 'star_keypoints', '../data/results/dsc07631/harris_star_matches.csv')

In [60]:
df_ss = compare_and_save_match_points(df_sift, df_star, 'sift_keypoints', 'star_keypoints', '../data/results/dsc07631/sift_star_matches.csv')

## Segundo Experimento

In [389]:
df_harris.head()

harris_threshold  harris_blockSize  harris_ksize  harris_k  \
0              0.01                 2             3      0.02   
1              0.01                 2             3      0.04   
2              0.01                 2             3      0.16   
3              0.01                 2             5      0.02   
4              0.01                 2             5      0.04   

   harris_qtd_keypoints                                   harris_keypoints  
0                 10493  [(71.0, 0.0), (72.0, 0.0), (73.0, 0.0), (74.0,...  
1                  9288  [(71.0, 0.0), (72.0, 0.0), (73.0, 0.0), (74.0,...  
2                  5947  [(98.0, 2.0), (99.0, 2.0), (100.0, 2.0), (98.0...  
3                  8844  [(71.0, 0.0), (72.0, 0.0), (73.0, 0.0), (74.0,...  
4                  7534  [(71.0, 0.0), (72.0, 0.0), (73.0, 0.0), (74.0,...

In [ ]:
matches_hs = computeDistacesKeypoints(h_kp, s_kp, threshold=2)
matches_ho = computeDistacesKeypoints(h_kp, o_kp, threshold=2)
matches_so = computeDistacesKeypoints(s_kp, o_kp, threshold=2)

## Primeiro experimento
- Rodando com os parâmetros default dos algoritmos

In [271]:
image = cv2.imread('../data/imgs/dsc07631.jpg')
h_kp, harris_image = detectHarrisKeypoints(image)
s_kp, sift_image = detectSIFTKeypoints(image)
o_kp, orb_image = detectStarKeypoints(image)


### threshold para matches de detectores 1

In [272]:
matches_hs = computeDistacesKeypoints(h_kp, s_kp, threshold=1)
matches_ho = computeDistacesKeypoints(h_kp, o_kp, threshold=1)
matches_so = computeDistacesKeypoints(s_kp, o_kp, threshold=1)

In [258]:
print('----- Resultados -----')
print(f'QTD Harris Keypoints:   {len(h_kp)}')
print(f'QTD SIFT Keypoints:   {len(s_kp)}')
print(f'QTD ORB Keypoints:   {len(o_kp)}')
print('----- Matches -----')
print(f'Matches Keypoints Harris/SIFT:   {len(matches_hs)}')
print(f'Matches Keypoints Harris/ORB:   {len(matches_ho)}')
print(f'Matches Keypoints SIFT/ORB:   {len(matches_so)}')

----- Resultados -----
QTD Harris Keypoints:   9288
QTD SIFT Keypoints:   1518
QTD ORB Keypoints:   500
----- Matches -----
Matches Keypoints Harris/SIFT:   645
Matches Keypoints Harris/ORB:   666
Matches Keypoints SIFT/ORB:   80


In [259]:
kp_matches_hs = [cv2.KeyPoint(x[0], x[1], 13) for x in matches_hs]
kp_matches_ho = [cv2.KeyPoint(x[0], x[1], 13) for x in matches_ho]
kp_matches_so = [cv2.KeyPoint(x[0], x[1], 13) for x in matches_so]

In [260]:
kp1_image = cv2.drawKeypoints(image, kp_matches_hs, None, color=(0, 0, 255), flags=0)
kp2_image = cv2.drawKeypoints(image, kp_matches_ho, None, color=(0, 255, 0), flags=0)
kp3_image = cv2.drawKeypoints(image, kp_matches_so, None, color=(255, 0, 0), flags=0)

In [262]:
# cv2.imshow('ORB', kp_matches_hs)

### threshold para matches de detectores 2

In [263]:
matches_hs = computeDistacesKeypoints(h_kp, s_kp, threshold=2)
matches_ho = computeDistacesKeypoints(h_kp, o_kp, threshold=2)
matches_so = computeDistacesKeypoints(s_kp, o_kp, threshold=2)

In [264]:
print('----- Resultados -----')
print(f'QTD Harris Keypoints:   {len(h_kp)}')
print(f'QTD SIFT Keypoints:   {len(s_kp)}')
print(f'QTD ORB Keypoints:   {len(o_kp)}')
print('----- Matches -----')
print(f'Matches Keypoints Harris/SIFT:   {len(matches_hs)}')
print(f'Matches Keypoints Harris/ORB:   {len(matches_ho)}')
print(f'Matches Keypoints SIFT/ORB:   {len(matches_so)}')

----- Resultados -----
QTD Harris Keypoints:   9288
QTD SIFT Keypoints:   1518
QTD ORB Keypoints:   500
----- Matches -----
Matches Keypoints Harris/SIFT:   2342
Matches Keypoints Harris/ORB:   1430
Matches Keypoints SIFT/ORB:   125


In [265]:
kp_matches_hs = [cv2.KeyPoint(x[0], x[1], 13) for x in matches_hs]
kp_matches_ho = [cv2.KeyPoint(x[0], x[1], 13) for x in matches_ho]
kp_matches_so = [cv2.KeyPoint(x[0], x[1], 13) for x in matches_so]

In [266]:
kp1_image = cv2.drawKeypoints(image, kp_matches_hs, None, color=(0, 0, 255), flags=0)
kp2_image = cv2.drawKeypoints(image, kp_matches_ho, None, color=(0, 255, 0), flags=0)
kp3_image = cv2.drawKeypoints(image, kp_matches_so, None, color=(255, 0, 0), flags=0)

In [268]:
# cv2.imshow('Harris/SIFT', kp1_image)
# cv2.waitKey() 

# Comparando Descritores

In [478]:
import copy

def calculate_slope(pt1, pt2):
    slope = (pt2[1] - pt1[1]) / (pt2[0] - pt1[0])
    return slope


def verify_slope(match, trainKeypoints, queryKeypoints, slope1, slope2):
    slope = calculate_slope(trainKeypoints[match.trainIdx].pt, queryKeypoints[match.queryIdx].pt) 
    if slope <= slope2 and slope >= slope1:
        return True
    else:
        return False



def verify_dist(match, trainKeypoints, queryKeypoints, dist1, dist2):
    point1 = np.asarray(trainKeypoints[match.trainIdx].pt)
    point2 = np.asarray(queryKeypoints[match.queryIdx].pt)

    dist = np.linalg.norm(point1 - point2)

    if dist <= dist2 and dist >= dist1:
        return True
    else:
        return False


def calculate_slope_list(matches, matchesMask, trainKeypoints, queryKeypoints):
    slope_list = [calculate_slope(trainKeypoints[matches[i][0].trainIdx].pt, queryKeypoints[matches[i][0].queryIdx].pt) for i, m in enumerate(matchesMask)]
    slope_list_mask = [calculate_slope(trainKeypoints[matches[i][0].trainIdx].pt, queryKeypoints[matches[i][0].queryIdx].pt) for i, m in enumerate(matchesMask) if m[0] > 0]

    return slope_list, slope_list_mask


def calculate_dist_list(matches, matchesMask, trainKeypoints, queryKeypoints):
    kps_train = [(trainKeypoints[matches[i][0].trainIdx].pt[0], trainKeypoints[matches[i][0].trainIdx].pt[1]) for i, m in enumerate(matchesMask)]
    kps_query = [(queryKeypoints[matches[i][0].queryIdx].pt[0], queryKeypoints[matches[i][0].queryIdx].pt[1]) for i, m in enumerate(matchesMask)]

    kps_train_ = [(trainKeypoints[matches[i][0].trainIdx].pt[0], trainKeypoints[matches[i][0].trainIdx].pt[1]) for i, m in enumerate(matchesMask) if m[0] > 0]
    kps_query_ = [(queryKeypoints[matches[i][0].queryIdx].pt[0], queryKeypoints[matches[i][0].queryIdx].pt[1]) for i, m in enumerate(matchesMask) if m[0] > 0]
    
    array_pts_train = np.asarray(kps_train)
    array_pts_query = np.asarray(kps_query)

    array_pts_train_ = np.asarray(kps_train_)
    array_pts_query_ = np.asarray(kps_query_)

    dists = [np.linalg.norm(point1 - point2) for point1, point2 in zip(array_pts_train, array_pts_query)]
    dists_mask = [np.linalg.norm(point1 - point2) for point1, point2 in zip(array_pts_train_, array_pts_query_)]

    return dists, dists_mask


def filter_matches_by_percentile(matches, matchesMask, trainKeypoints, queryKeypoints, q1, q2):
    slope_list, slope_list_ = calculate_slope_list(matches, matchesMask, trainKeypoints, queryKeypoints)
    dists, dists_ = calculate_dist_list(matches, matchesMask, trainKeypoints, queryKeypoints)

    s1_, s2_ = np.percentile(slope_list_, [q1 ,q2])
    d1_, d2_ = np.percentile(dists_, [q1 ,q2])
    
    matchesMask_ = [ [1,0] if m[0] > 0 and verify_slope(matches[i][0], trainKeypoints, queryKeypoints, s1_, s2_) else [0,0] for i, m in enumerate(matchesMask)]
    matchesMask_ = [ [1,0] if m[0] > 0 and verify_dist(matches[i][0], trainKeypoints, queryKeypoints, d1_, d2_) else [0,0] for i, m in enumerate(matchesMask_)]

    qtd_matches = len(matches)
    qtd_matches_dlowe = len([m[0] for m in matchesMask if m[0] > 0 ])
    qtd_matches_filter = len([m[0] for m in matchesMask_ if m[0] > 0 ])

    qtd_fp_dlowe = qtd_matches - qtd_matches_dlowe
    qtd_fp_filter = qtd_matches_dlowe - qtd_matches_filter
    
    # norm = np.linalg.norm(data)  # Calculate the L2 norm of the data
    # normalized_data = data / norm

    var_dist = np.var([d for m, d in zip(matchesMask, dists) if m[0] > 0 ])
    var_slope = np.var([sl for m, sl in zip(matchesMask, slope_list) if m[0] > 0 ])

    # mismatch_train_keypoints = len(trainKeypoints) - qtd_matches
    # mismatch_query_keypoints = len(queryKeypoints) - qtd_matches

    return matchesMask_, qtd_matches, qtd_matches_dlowe, qtd_matches_filter, qtd_fp_dlowe, qtd_fp_filter, var_dist, var_slope


def filter_matches_by_variance(matches, trainKeypoints, queryKeypoints, var_dist, var_slope):
    matchesMask_ = [[0,0] for i in range(len(matches))]
    var_dist_ = -1
    var_slope_ = -1
    ratio_test_ = -1
    
    for ratio_test in np.arange(0.1, 1., 0.01):
        matchesMask = [[0,0] for i in range(len(matches))]

        for i,(m,n) in enumerate(matches):
            if m.distance < ratio_test*n.distance:
                matchesMask[i]=[1,0]

        slope_list, slope_list_ = calculate_slope_list(matches, matchesMask, trainKeypoints, queryKeypoints)
        dists, dists_ = calculate_dist_list(matches, matchesMask, trainKeypoints, queryKeypoints)

        var_d = np.var(dists_)
        var_s = np.var(slope_list_)

        if var_d <= var_dist and var_s <= var_slope:
            ratio_test_ = round(copy.copy(ratio_test), 2)
            var_dist_ = var_d
            var_slope_ = var_s
            matchesMask_ = [m for m in matchesMask]
        
    
    qtd_matches = len(matches)
    qtd_matches_dlowe = len([m[0] for m in matchesMask_ if m[0] > 0 ])

    qtd_fp_dlowe = qtd_matches - qtd_matches_dlowe

    return matchesMask_, ratio_test_, qtd_matches, qtd_matches_dlowe, qtd_fp_dlowe, var_dist_, var_slope_



def draw_matches(train_img, query_img, trainKeypoints, queryKeypoints, matches, matchesMask):
    kps_train = [[trainKeypoints[matches[i][0].trainIdx].pt[0], trainKeypoints[matches[i][0].trainIdx].pt[1]] for i, m in enumerate(matchesMask)]
    kps_query = [[queryKeypoints[matches[i][0].queryIdx].pt[0], queryKeypoints[matches[i][0].queryIdx].pt[1]] for i, m in enumerate(matchesMask)]

    # draw the tracks
    mask = np.zeros_like(train_img, 'uint8') 

    line = (0,255,0)
    point_true = (255,0,0)
    point_false = (0,0,255)
    frame = query_img.copy()
    
    for i, (m, query, train) in enumerate(zip(matchesMask, kps_query, kps_train)):
        a, b = query[0], query[1]
        c, d = train[0], train[1]
        
        a, b = int(a), int(b)
        c, d = int(c), int(d)
        
        if m[0] > 0:
            mask = cv2.line(mask, (a, b), (c, d), line, 2) 
            frame = cv2.circle(frame, (a, b), 4, point_true, -1)
        else:
            frame = cv2.circle(frame, (a, b), 4, point_false, -1)
    
    img = cv2.add(frame, mask)

    return img


In [479]:
def matchDetectedKeypoints(train_img, query_img, var_dist, var_slope, detector='harris', descriptor='orb', dect_kargs={}, des_kargs={}):
    query_img_bw = cv2.cvtColor(query_img, cv2.COLOR_BGR2GRAY) 
    train_img_bw = cv2.cvtColor(train_img, cv2.COLOR_BGR2GRAY)

    if descriptor == 'brief':
        des = cv2.xfeatures2d.BriefDescriptorExtractor_create(**des_kargs)
        norm_type = cv2.NORM_HAMMING
    elif descriptor == 'brisk':
        des = cv2.BRISK_create(**des_kargs)
        norm_type = cv2.NORM_HAMMING
    else:
        des = cv2.SIFT.create(**des_kargs)
        norm_type = cv2.NORM_L2
    
    if detector == 'star':
        func_var = detectStarKeypoints
    elif detector == 'harris':
        func_var = detectHarrisKeypoints
    else:
        func_var = detectSIFTKeypoints

    queryKeypoints, _ = func_var(query_img, **dect_kargs)
    trainKeypoints, _ = func_var(train_img, **dect_kargs)
    
    _,queryDescriptors = des.compute(query_img_bw, queryKeypoints) 
    _,trainDescriptors = des.compute(train_img_bw, trainKeypoints)


    matcher = cv2.BFMatcher(normType=norm_type, crossCheck=False) 
    matches = matcher.knnMatch(queryDescriptors,trainDescriptors, k=2) 

    # Need to draw only good matches, so create a mask
    # matchesMask = [[0,0] for i in range(len(matches))]

    # for i,(m,n) in enumerate(matches):
    #     if m.distance < ratio_test*n.distance:
    #         matchesMask[i]=[1,0]

    # m = filter_matches_by_percentile(matches, matchesMask, trainKeypoints, queryKeypoints, filter_slope[0], filter_slope[1])
    
    m = filter_matches_by_variance(matches, trainKeypoints, queryKeypoints, var_dist, var_slope)
    matchesMask_, ratio_test_, qtd_matches, qtd_matches_dlowe, qtd_fp_dlowe, var_dist_, var_slope_ = m 

    print('---- Resultado ---- ')
    print(f'Quantidade de keypoints train image: {len(trainKeypoints)}')
    print(f'Quantidade de keypoints query image: {len(queryKeypoints)}')
    print(f'Quantidade de matches: {qtd_matches}')
    print(f'Valor ratio test D.Lowe: {ratio_test_}')
    print(f'Quantidade de matches filtro D.Lowe: {qtd_matches_dlowe}')
    print(f'Quantidade de falso D.Lowe: {qtd_fp_dlowe}')
    print(f'Variância da distância: {var_dist_}')
    print(f'Variância da inclinação da linha: {var_slope_}')

    draw_params = dict(matchColor = (0,255,0),
                    singlePointColor = (255,0,0),
                    matchesMask = matchesMask_,
                    flags = cv2.DrawMatchesFlags_DEFAULT)
    
    # final_img = cv2.drawMatchesKnn(query_img,queryKeypoints,train_img,trainKeypoints,matches,None,**draw_params)

    final_img = draw_matches(train_img, query_img, trainKeypoints, queryKeypoints, matches, matchesMask_)

    
    final_img = cv2.resize(final_img, (480,640))

    return final_img 

    

In [480]:
params_sift = {
    'nfeatures': 100,
    'nOctaveLayers' : 1,
    'contrastThreshold' : 0.04,
    'edgeThreshold' : 20,
    'sigma' : 1.6
}

params_harris = {
    # 'image': [image],
    'threshold' : 0.2,# [0.005, 0.01, 0.05, 0.1, 0.2],
    'blockSize' : 6,#[2, 4, 6, 8],
    'ksize' : 7,#[3, 5, 7, 9],
    'k' : 0.16,#[0.02, 0.04, 0.08, 0.16]
}

params_brisk = {    
    # 'thresh': 100,	#AGAST detection threshold score.
    # 'octaves':200,	#detection octaves. Use 0 to do single scale.
    'radiusList': [8, 9, 10],	#defines the radii (in pixels) where the samples around a keypoint are taken (for keypoint scale 1).
    'numberList': [12, 16, 20],	#defines the number of sampling points on the sampling circle. Must be the same size as radiusList..
    'dMax': 2,	#threshold for the short pairings used for descriptor formation (in pixels for keypoint scale 1).
    'dMin': 1,	#threshold for the long pairings used for orientation determination (in pixels for keypoint scale 1).
    # 'indexChange': 1,	#index remapping of the bits.
}

In [481]:
query_img = cv2.imread('../data/imgs_teste/IMG_20231129_083413.jpg') 
train_img = cv2.imread('../data/imgs_teste/IMG_20231129_083404.jpg')
# query_img = cv2.imread('../data/imgs/dsc07632.jpg') 
# train_img = cv2.imread('../data/imgs/dsc07631.jpg') 
query_img_ = cv2.resize(query_img, (480,640))
train_img_ = cv2.resize(train_img, (480,640))

In [482]:
# final_img = matchDetectedKeypoints(train_img_, query_img_, 0.75, filter_slope=(0,100), detector='harris', descriptor='sift', dect_kargs=params_harris, des_kargs={})

In [496]:
final_img = matchDetectedKeypoints(train_img_, query_img_, 10, 1, detector='sift', descriptor='sift', dect_kargs={}, des_kargs={})

---- Resultado ---- 
Quantidade de keypoints train image: 316
Quantidade de keypoints query image: 350
Quantidade de matches: 350
Valor ratio test D.Lowe: 0.55
Quantidade de matches filtro D.Lowe: 148
Quantidade de falso D.Lowe: 202
Variância da distância: 9.628911904936926
Variância da inclinação da linha: 0.0031546559590156244


In [497]:
# Show the final image 
cv2.imshow("Matches", final_img) 
cv2.waitKey()

-1

# Comparando Fluxo Óptico

## Lucas-Kanade

In [1138]:
import numpy as np 
import cv2 

train_img = cv2.imread('../data/imgs_teste/IMG_20231129_083404.jpg') 
query_img = cv2.imread('../data/imgs_teste/IMG_20231129_083413.jpg')
# query_img = cv2.imread('../data/imgs/dsc07632.jpg') 
# train_img = cv2.imread('../data/imgs/dsc07631.jpg')  
train_img_ = cv2.resize(train_img, (480,640))
query_img_ = cv2.resize(query_img, (480,640))

# params for corner detection 
feature_params = dict( maxCorners = 100, 
                       qualityLevel = 0.2, 
                       minDistance = 7, 
                       blockSize = 7,
                       useHarrisDetector = False) 
  
# Parameters for lucas kanade optical flow 
lk_params = dict( winSize = (16, 16), 
                  maxLevel = 2, 
                  criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 
                              10, 0.03)) 
  
# Create some random colors 
color = np.random.randint(0, 255, (100, 3)) 
print(color)
# Take first frame and find corners in it 
old_frame = train_img_ 
old_gray = cv2.cvtColor(old_frame, 
                        cv2.COLOR_BGR2GRAY)

sift = cv2.SIFT_create(nfeatures=100)

p0 = sift.detect(old_gray)
p0 = np.asarray([[[np.float32(kp.pt[0]), np.float32(kp.pt[1])]] for kp in p0])

# p0 = cv2.goodFeaturesToTrack(old_gray, mask = None, **feature_params) 

print(p0)

# Create a mask image for drawing purposes 
mask = np.zeros_like(old_frame, 'uint8') 
  

frame = query_img_ 
frame_gray = cv2.cvtColor(frame, 
                            cv2.COLOR_BGR2GRAY) 

# calculate optical flow 
p1, st, err = cv2.calcOpticalFlowPyrLK(old_gray, 
                                        frame_gray, 
                                        p0, None, 
                                        **lk_params) 

# Select good points 
good_new = p1[st == 1] 
good_old = p0[st == 1] 

# draw the tracks
for i, (new, old) in enumerate(zip(good_new,  
                                    good_old)):
    a, b = new.ravel() 
    c, d = old.ravel()
    
    a, b = int(a), int(b)
    c, d = int(c), int(d)


    mask = cv2.line(mask, (a, b), (c, d), 
                    color[0].tolist(), 2) 
        
    frame = cv2.circle(frame, (a, b), 5, 
                        color[0].tolist(), -1) 
        
img = cv2.add(frame, mask) 

cv2.imshow('frame', img)
cv2.waitKey()

# # Updating Previous frame and points  
# old_gray = frame_gray.copy() 
# p0 = good_new.reshape(-1, 1, 2) 


[[229  41 190]
 [202 214 159]
 [ 86 208 177]
 [165 216 246]
 [ 85   3 206]
 [240 193 161]
 [ 36 214 124]
 [ 79 202 122]
 [200 220 170]
 [254  80  22]
 [ 19 210 170]
 [186 179 248]
 [ 29 226   8]
 [ 88 240 106]
 [ 63  87 137]
 [ 66 144  46]
 [ 40 202   0]
 [132 128 104]
 [132  64 246]
 [ 68 111 150]
 [ 88 150 137]
 [ 83  98 127]
 [  7 161 139]
 [  9  54 238]
 [ 93  97 235]
 [ 52 243 174]
 [112  80  76]
 [ 11  11 249]
 [218 252  89]
 [207  30  57]
 [ 65   1  92]
 [207  20  41]
 [221   0 164]
 [192  94 136]
 [181 168 178]
 [ 42 230  95]
 [114  58  92]
 [214 128 254]
 [183 218 136]
 [110 165 109]
 [  7  74   3]
 [248  59  31]
 [144  61 200]
 [ 20 143  60]
 [ 88 248 129]
 [187 111   7]
 [ 20 138 208]
 [100 243  36]
 [ 28  65 232]
 [ 17  52  38]
 [227 172  94]
 [ 23  38   7]
 [ 64  81 183]
 [227 241   6]
 [ 34  57  63]
 [162 239 242]
 [ 58 176   3]
 [132 125 182]
 [ 28 237  61]
 [250 125   9]
 [235  92 132]
 [144  78 209]
 [181  90 204]
 [118  84 211]
 [ 48 122 157]
 [102 114 122]
 [ 56   3 

-1

## Horn-Schunk 

In [498]:
def draw_flow(img, flow, step=16):
    h, w = img.shape[:2]
    y, x = np.mgrid[step / 2:h:step, step / 2:w:step].reshape(2, -1).astype(int)
    fx, fy = flow[y, x].T
    lines = np.vstack([x, y, x + fx, y + fy]).T.reshape(-1, 2, 2)
    lines = np.int32(lines + 0.5)
    vis = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    cv2.polylines(vis, lines, 0, (0, 255, 0))
    for (x1, y1), (x2, y2) in lines:
        cv2.circle(vis, (x1, y1), 1, (0, 255, 0), -1)
    return vis

In [499]:
# Importing libraries
import cv2
import numpy as np

# train_img = cv2.imread('../data/imgs_teste/IMG_20231129_083404.jpg') 
# query_img = cv2.imread('../data/imgs_teste/IMG_20231129_083413.jpg')
query_img = cv2.imread('../data/imgs/dsc07632.jpg') 
train_img = cv2.imread('../data/imgs/dsc07631.jpg')  
train_img_ = cv2.resize(train_img, (480,640))
query_img_ = cv2.resize(query_img, (480,640))

# Convert to gray scale
prvs = cv2.cvtColor(train_img_, cv2.COLOR_BGR2GRAY)
# Create mask
hsv_mask = np.zeros_like(train_img_)
# Make image saturation to a maximum value
hsv_mask[..., 1] = 255
 
# Capture another frame and convert to gray scale
next = cv2.cvtColor(query_img_, cv2.COLOR_BGR2GRAY)

# Optical flow is now calculated
flow = cv2.calcOpticalFlowFarneback(prvs, next, None, 0.5, 3, 15, 3, 5, 1.2, 0)

mapped_img = draw_flow(next, flow, step=16)

cv2.imshow('frame2', mapped_img)
cv2.waitKey()


-1